version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: tasks_db
    ports:
      - "5434:5432"  # Используем один и тот же порт
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin", "-d", "tasks_db"]
      interval: 5s
      retries: 5

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy  # Ждём готовности БД перед запуском API
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: secret
      DB_NAME: tasks_db
    ports:
      - "8081:8080"

  migrate:
    image: migrate/migrate
    volumes:
      - ./db/migrations:/migrations
    depends_on:
      db:
        condition: service_healthy  # Ждём, пока БД будет готова
    entrypoint: 
      - "migrate" 
      - "-path" 
      - "/migrations" 
      - "-database" 
      - "postgres://admin:secret@db:5432/tasks_db?sslmode=disable" 
      - "up"

volumes:
  db_data:
